# Generated by Django 6.0.7 on 2026-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('AUD', 'Australian Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('IC', 'IC'), ('NPR', 'Nepalese Rupee')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('AUD', 'Australian Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('IC', 'IC'), ('NPR', 'Nepalese Rupee')], default='USD', max_length=10),
        ),
    ]
