# Generated by Django 5.2.16 on 2026-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_receipt_income_receipt_alter_budget_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='billreminder',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='savingsgoal',
            unique_together={('user', 'name')},
        ),
    ]
