# Generated by Django 5.2.16 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_user_phone_number_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(
                condition=models.Q(('amount_limit__gte', 0)),
                name='budget_amount_limit_non_negative',
            ),
        ),
    ]
