# Generated by Django 5.2.16 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_budget_amount_limit_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='income_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
    ]
