# Generated by Django 5.2.16 on 2026-08-26

import finance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_income_amount_positive_expense_amount_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[finance.validators.validate_com_email]),
        ),
    ]
